name: Hello Actions

on: 
  push:
    branches: 
      - master
  pull_request:
    types: [closed]
env:
  name: DannyBoy
jobs:  
  build:

    runs-on: ubuntu-latest
    if: github.even_name == "pull_request"
    needs: build
    env:
      name: Dan
    steps:
    - name: Run a one-line script
      run: echo Hello, $name!   
        
  pull_request_only:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
